{% if cookiecutter.use_pre_commit == 'y' %}
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

{% if cookiecutter.use_black == 'y' %}
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
{% endif %}

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

{% if cookiecutter.use_mypy == 'y' %}
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
{% endif %}
{% endif %} 