[tool.poetry]
name = "{{ cookiecutter.project_slug }}"
version = "0.1.0"
description = "{{ cookiecutter.description }}"
authors = ["{{ cookiecutter.author }} <{{ cookiecutter.email }}>"]
readme = "README.md"
packages = [{include = "{{ cookiecutter.package_name }}", from = "src"}]

[tool.poetry.dependencies]
python = "^{{ cookiecutter.python_version }}"
{% if cookiecutter.use_mkdocs == 'y' %}
mkdocs = "^1.5.0"
mkdocs-material = "^9.0.0"
mkdocstrings = {extras = ["python"], version = "^0.24.0"}
{% endif %}

[tool.poetry.group.dev.dependencies]
{% if cookiecutter.use_pytest == 'y' %}
pytest = "^7.0"
pytest-cov = "^4.0"
{% endif %}
{% if cookiecutter.use_black == 'y' %}
black = "^23.0"
{% endif %}
{% if cookiecutter.use_mypy == 'y' %}
mypy = "^1.0"
{% endif %}
{% if cookiecutter.use_pre_commit == 'y' %}
pre-commit = "^3.0"
{% endif %}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

{% if cookiecutter.use_black == 'y' %}
[tool.black]
line-length = 88
target-version = ["py38"]
include = '\.pyi?$'
{% endif %}

{% if cookiecutter.use_mypy == 'y' %}
[tool.mypy]
python_version = "{{ cookiecutter.python_version }}"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
{% endif %}

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=src --cov-report=term-missing"
pythonpath = ["."]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88 