name: 更新文档

on:
  push:
    paths:
      - 'src/**/*.py'        # 源代码变更
      - 'pyproject.toml'     # 项目配置变更
      - 'examples/**/*.py'   # 示例代码变更
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'src/**/*.py'
      - 'pyproject.toml'
      - 'examples/**/*.py'
  schedule:
    - cron: '0 0 * * 1'      # 每周一自动更新
  workflow_dispatch:          # 手动触发选项

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        
    - name: 检查更新类型
      id: check-updates
      run: |
        python .github/scripts/check_update_type.py
        
    - name: 更新文档
      if: steps.check-updates.outputs.should_update == 'true'
      run: |
        python .github/scripts/enhanced_readme_updater.py
        
    - name: 提交更改
      if: steps.check-updates.outputs.should_update == 'true' && github.event_name != 'pull_request'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "docs: 更新项目文档 [skip ci]"
        
    - name: 推送更改
      if: steps.check-updates.outputs.should_update == 'true' && github.event_name != 'pull_request'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }} 